name: simple_chat
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  djangoflow_auth: ^0.4.0
  djangoflow_openapi: ^0.1.22
  dio: ^5.4.2
  flutter_bloc: ^8.1.5
  flutter_list_bloc: ^4.1.4
  freezed_annotation: ^2.4.1
  hydrated_bloc: ^9.1.5
  json_annotation: ^4.8.1
  list_bloc: ^3.1.3
  openapi_repository_annotations: ^1.2.4
  path_provider: ^2.1.2
  progress_builder: ^1.1.3
  reactive_forms: ^16.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  icons_launcher: ^2.1.7
  openapi_repository: ^3.4.5

dependency_overrides:
  # use local dependency for djangoflow_openapi to override the one from pub.dev
  djangoflow_openapi:
    path: ./packages/djangoflow_openapi

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo/
